name: Build image from release tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Build and push Docker image
      run: |
        docker login -u mreiger -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -t mreiger/kubernetes-audit-tailer:${GITHUB_REF##*/} .
        docker push mreiger/kubernetes-audit-tailer:${GITHUB_REF##*/}
